name: cosima
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nodejs
  - cartopy
  - cmocean
  - dask=2.20.0
  - distributed=2.20.0
  - dask-labextension>=2.0.0
  - dask-ml
  - jupyterhub
  - jupyterlab>=2.0.0
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - scipy
  - xarray
  - numpy>=1.18.1
  - h5py
  - scipy>=1.3.0
  - toolz
  - bokeh>=2.0.0
  - notebook
  - Pillow
  - pandas>=1.0.1
  - pandas-datareader
  - pytables
  - scikit-learn>=0.22.1
  - scikit-image>=0.15.0
  - snakeviz
  - ujson
  - pip
  - s3fs
  - fastparquet
  - ipywidgets>=7.5
  - cachey
  - python-graphviz
  - zarr
